package com.alibaba.test.steed.dao;

import com.alibaba.test.steed.model.Result;
import com.alibaba.test.steed.model.ResultExample;
import com.alibaba.test.steed.model.ResultWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int countByExample(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int deleteByExample(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int insert(ResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int insertSelective(ResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    List<ResultWithBLOBs> selectByExampleWithBLOBs(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    List<Result> selectByExample(ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    ResultWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") ResultWithBLOBs record, @Param("example") ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ResultWithBLOBs record, @Param("example") ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByExample(@Param("record") Result record, @Param("example") ResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByPrimaryKeySelective(ResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByPrimaryKey(Result record);
}