package com.alibaba.test.steed.dao;

import com.alibaba.test.steed.model.Rule;
import com.alibaba.test.steed.model.RuleExample;
import com.alibaba.test.steed.model.RuleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface RuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int countByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int deleteByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int insert(RuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int insertSelective(RuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    List<RuleWithBLOBs> selectByExampleWithBLOBs(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    List<Rule> selectByExample(RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    RuleWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") RuleWithBLOBs record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") RuleWithBLOBs record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByExample(@Param("record") Rule record, @Param("example") RuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByPrimaryKeySelective(RuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(RuleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    int updateByPrimaryKey(Rule record);
}