package com.alibaba.test.steed.model;

public class ResultWithBLOBs extends Result {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.request
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String request;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.response
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result.rule_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String ruleResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public ResultWithBLOBs(Integer id, Integer taskid, Integer caseid, String request, String response, String ruleResult) {
        super(id, taskid, caseid);
        this.request = request;
        this.response = response;
        this.ruleResult = ruleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public ResultWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.request
     *
     * @return the value of result.request
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.request
     *
     * @param request the value for result.request
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.response
     *
     * @return the value of result.response
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.response
     *
     * @param response the value for result.response
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result.rule_result
     *
     * @return the value of result.rule_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getRuleResult() {
        return ruleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result.rule_result
     *
     * @param ruleResult the value for result.rule_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setRuleResult(String ruleResult) {
        this.ruleResult = ruleResult == null ? null : ruleResult.trim();
    }
}