package com.alibaba.test.steed.model;

import java.util.Date;

public class RuleWithBLOBs extends Rule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.r_when
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String rWhen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.r_verify
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String rVerify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.r_then
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String rThen;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public RuleWithBLOBs(Integer id, String name, String tags, String category, Integer level, Byte enable, Byte retry, String owner, Date modify, String application, Byte debug, String rWhen, String rVerify, String rThen) {
        super(id, name, tags, category, level, enable, retry, owner, modify, application, debug);
        this.rWhen = rWhen;
        this.rVerify = rVerify;
        this.rThen = rThen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public RuleWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.r_when
     *
     * @return the value of rule.r_when
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getrWhen() {
        return rWhen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.r_when
     *
     * @param rWhen the value for rule.r_when
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setrWhen(String rWhen) {
        this.rWhen = rWhen == null ? null : rWhen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.r_verify
     *
     * @return the value of rule.r_verify
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getrVerify() {
        return rVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.r_verify
     *
     * @param rVerify the value for rule.r_verify
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setrVerify(String rVerify) {
        this.rVerify = rVerify == null ? null : rVerify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.r_then
     *
     * @return the value of rule.r_then
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getrThen() {
        return rThen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.r_then
     *
     * @param rThen the value for rule.r_then
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setrThen(String rThen) {
        this.rThen = rThen == null ? null : rThen.trim();
    }
}