package com.alibaba.test.steed.model;

import java.util.Date;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.owner
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.host
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.start_time
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.end_time
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private Integer taskResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_info
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String taskInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.test_data
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String testData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.rule_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    private String ruleResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public Task(Integer id, String owner, String host, Date startTime, Date endTime, Integer taskResult, String taskInfo, String testData, String ruleResult) {
        this.id = id;
        this.owner = owner;
        this.host = host;
        this.startTime = startTime;
        this.endTime = endTime;
        this.taskResult = taskResult;
        this.taskInfo = taskInfo;
        this.testData = testData;
        this.ruleResult = ruleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public Task() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.owner
     *
     * @return the value of task.owner
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.owner
     *
     * @param owner the value for task.owner
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.host
     *
     * @return the value of task.host
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.host
     *
     * @param host the value for task.host
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.start_time
     *
     * @return the value of task.start_time
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.start_time
     *
     * @param startTime the value for task.start_time
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.end_time
     *
     * @return the value of task.end_time
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.end_time
     *
     * @param endTime the value for task.end_time
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_result
     *
     * @return the value of task.task_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public Integer getTaskResult() {
        return taskResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_result
     *
     * @param taskResult the value for task.task_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setTaskResult(Integer taskResult) {
        this.taskResult = taskResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_info
     *
     * @return the value of task.task_info
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getTaskInfo() {
        return taskInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_info
     *
     * @param taskInfo the value for task.task_info
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setTaskInfo(String taskInfo) {
        this.taskInfo = taskInfo == null ? null : taskInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.test_data
     *
     * @return the value of task.test_data
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getTestData() {
        return testData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.test_data
     *
     * @param testData the value for task.test_data
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setTestData(String testData) {
        this.testData = testData == null ? null : testData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.rule_result
     *
     * @return the value of task.rule_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public String getRuleResult() {
        return ruleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.rule_result
     *
     * @param ruleResult the value for task.rule_result
     *
     * @mbggenerated Mon Sep 02 16:57:20 CST 2019
     */
    public void setRuleResult(String ruleResult) {
        this.ruleResult = ruleResult == null ? null : ruleResult.trim();
    }
}